### ISSUE TITLE
Error! Bad return status for module build on kernel

### ISSUE THREAD

**Issue by nikandriko** [lyatiss/tcp_probe_plus#3]
Hi, I'm consistently getting the following error across both 2 Raspberry Pi 3s and a Debian _**4.9.0.7-amd64**_ VM. This issue has been mentioned [elsewhere](https://github.com/abdulsamad786/TCP-Network-Connection-Monitoring-with-Python/issues/1).

Here's the console lines:

```
root@tcpprobeplus:/usr/src# sudo dkms build tcp_probe_plus/1.1.6
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j1 KERNELRELEASE=4.9.0-7-amd64 -C /lib/modules/4.9.0-7-amd64/build SUBDIRS=/var/lib/dkms/tcp_probe_plus/1.1.6/build modules...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.9.0-7-amd64 (x86_64)
Consult /var/lib/dkms/tcp_probe_plus/1.1.6/build/make.log for more information.
```

And the contents of the referenced log file above, i.e. ```/var/lib/dkms/tcp_probe_plus/1.1.6/build/make.log```

```
DKMS make.log for tcp_probe_plus-1.1.6 for kernel 4.9.0-7-amd64 (x86_64)
Fri Nov 23 17:44:55 EST 2018
make: Entering directory '/usr/src/linux-headers-4.9.0-7-amd64'
  CC [M]  /var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.o
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c: In function ‘tcp_flow_find’:
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:35: error: implicit declaration of function ‘__get_cpu_var’ [-Werror=implicit-function-declaration]
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                   ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:258:3: note: in expansion of macro ‘TCPPROBE_STAT_INC’
   TCPPROBE_STAT_INC(found);
   ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘found’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:258:3: note: in expansion of macro ‘TCPPROBE_STAT_INC’
   TCPPROBE_STAT_INC(found);
   ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘searched’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:261:4: note: in expansion of macro ‘TCPPROBE_STAT_INC’
    TCPPROBE_STAT_INC(searched);
    ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘notfound’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:263:2: note: in expansion of macro ‘TCPPROBE_STAT_INC’
  TCPPROBE_STAT_INC(notfound);
  ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c: In function ‘tcp_hash_flow_alloc’:
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘conn_memory_limit’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:289:4: note: in expansion of macro ‘TCPPROBE_STAT_INC’
    TCPPROBE_STAT_INC(conn_memory_limit);
    ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c: In function ‘write_flow’:
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘ack_drop_ring_full’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:440:4: note: in expansion of macro ‘TCPPROBE_STAT_INC’
    TCPPROBE_STAT_INC(ack_drop_ring_full);
    ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c: In function ‘jtcp_done’:
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘reset_flows’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:522:2: note: in expansion of macro ‘TCPPROBE_STAT_INC’
  TCPPROBE_STAT_INC(reset_flows);
  ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c: In function ‘jtcp_rcv_established’:
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘ack_drop_purge’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:585:4: note: in expansion of macro ‘TCPPROBE_STAT_INC’
    TCPPROBE_STAT_INC(ack_drop_purge);
    ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘conn_maxflow_limit’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:593:3: note: in expansion of macro ‘TCPPROBE_STAT_INC’
   TCPPROBE_STAT_INC(conn_maxflow_limit);
   ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c: In function ‘tcpprobe_read’:
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘multiple_readers’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:727:3: note: in expansion of macro ‘TCPPROBE_STAT_INC’
   TCPPROBE_STAT_INC(multiple_readers);
   ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:152:63: error: request for member ‘copy_error’ in something not a structure or union
 #define TCPPROBE_STAT_INC(count) (__get_cpu_var(tcpprobe_stat).count++)
                                                               ^
/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.c:746:3: note: in expansion of macro ‘TCPPROBE_STAT_INC’
   TCPPROBE_STAT_INC(copy_error);
   ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.9.0-7-common/scripts/Makefile.build:307: recipe for target '/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.o' failed
make[3]: *** [/var/lib/dkms/tcp_probe_plus/1.1.6/build/tcp_probe_plus.o] Error 1
/usr/src/linux-headers-4.9.0-7-common/Makefile:1526: recipe for target '_module_/var/lib/dkms/tcp_probe_plus/1.1.6/build' failed
make[2]: *** [_module_/var/lib/dkms/tcp_probe_plus/1.1.6/build] Error 2
Makefile:152: recipe for target 'sub-make' failed
make[1]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/usr/src/linux-headers-4.9.0-7-amd64'

```
